project:
  type: website
  output-dir: docs
  preview: 
    port: 4200
    browser: true
    navigate: true
        
format:
  html:
    theme: lux
    css: styles.css
    toc: true

website:
  title: "Rahul Menon"
  search: false
  navbar:
    background: primary
    left:
      - text: Projects 
        href: projects.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/rahulmenon1758/
      - icon: github
        href: https://github.com/dataexplorerRahul

editor:
  render-on-save: true


